// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyProject.Todo.Database;

namespace StudyProject.Todo.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190807134949_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("StudyProject.Todo.Database.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.HasKey("Guid");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("f6c8ef7e-9650-47a9-8fac-091733374b90"),
                            IsComplete = true,
                            Name = "name1"
                        },
                        new
                        {
                            Guid = new Guid("9cf69362-6575-4178-b593-d2baf34ec1f8"),
                            IsComplete = false,
                            Name = "name2"
                        },
                        new
                        {
                            Guid = new Guid("e590b122-eab2-422d-944b-3324d664eddc"),
                            IsComplete = true,
                            Name = "name3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
